name: Hello World

on: push

jobs:
  first_job:
    name: hello-job
    runs-on: ubuntu-latest
    steps:
    - name: Echo text
      run: | 
        echo "Hello, world!"
        echo "test2"

      
